# Generated by Django 3.1.1 on 2022-01-30 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0010_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
