# Generated by Django 3.1.1 on 2022-02-01 07:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main', '0013_collabs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='collabs',
            new_name='collab',
        ),
    ]
