# Generated by Django 3.1.1 on 2022-02-01 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main', '0015_collab_requested_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collab',
            name='requested_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
