# Generated by Django 3.1.1 on 2022-02-04 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0017_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_message',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='notification',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
