# Generated by Django 3.1.1 on 2022-02-04 09:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0019_auto_20220204_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 4, 9, 54, 23, 307213, tzinfo=utc)),
        ),
    ]
