# Generated by Django 4.0.2 on 2022-02-10 06:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0027_notification_notificaion_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='notificaion_from',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 10, 6, 0, 6, 275075, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project_comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 10, 6, 0, 6, 278091, tzinfo=utc)),
        ),
    ]
