# Generated by Django 4.0.2 on 2022-02-10 06:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0034_alter_notification_notification_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='notificaion_from',
            new_name='notification_from',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 10, 6, 30, 10, 142830, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project_comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 10, 6, 30, 10, 144825, tzinfo=utc)),
        ),
    ]
